version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_name_development
      MYSQL_USERNAME: root
    ports:
      - "3306:3306"
    volumes:
      - .mysql-data:/var/lib/mysql
  web:
    environment:
      - SPROCKETS_CACHE=/cache
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app_name
    ports:
      - "3000:3000"
    links:
      - db